workdir: /mnt/lab_data2/atwang/data/encode_scatac/test_all_4/

max_threads_per_rule: 4
seed: 8757647

### END-TO-END FULL RUN ###

genome: hg38

samples:
  reprog-D14:
    technology: 10x
    fastq:
      R1: /oak/stanford/groups/akundaje/surag/projects/scATAC-reprog/fastq/D14/D14_S8_L001_R1_001.fastq.gz
      R2: /oak/stanford/groups/akundaje/surag/projects/scATAC-reprog/fastq/D14/D14_S8_L001_R2_001.fastq.gz
      R3: /oak/stanford/groups/akundaje/surag/projects/scATAC-reprog/fastq/D14/D14_S8_L001_R3_001.fastq.gz
    bc_whitelist: 
      R2: /srv/scratch/surag/chromap_misc/737K-cratac-v1.rc.txt
    bc_revcomp: 
      R2: False
    max_barcode_dist: 1

  multiome-ENCSR332XEW:
    technology: multiome
    fastq:
      R1: /srv/www/kundaje/surag/ENCODE_scatac/data/multiome_ENCSR332XEW/R1_ENCFF159ZRF.fastq.gz
      R2: /srv/www/kundaje/surag/ENCODE_scatac/data/multiome_ENCSR332XEW/BC_ENCFF925EOG.fastq.gz
      R3: /srv/www/kundaje/surag/ENCODE_scatac/data/multiome_ENCSR332XEW/R2_ENCFF673XYW.fastq.gz
    bc_whitelist: 
      R2: /srv/www/kundaje/surag/resources/737K-arc-v1.txt.gz
    bc_revcomp: 
      R2: False
    max_barcode_dist: 1

  ren-raw-SM-A8CPH:
    technology: ren
    fastq:
      R1: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/fastq/Undetermined_S0_L002_R1_001.fastq.gz
      R2: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/fastq/Undetermined_S0_L002_R2_001.fastq.gz
      I1: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/fastq/Undetermined_S0_L002_I1_001.fastq.gz
      I2: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/fastq/Undetermined_S0_L002_I2_001.fastq.gz
    bc_whitelist: 
      I1: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/barcodes/ren_barcodes_T7_SM-A8CPH.tsv
      I2: /oak/stanford/groups/akundaje/atwang/encode_scatac/ren/barcodes/ren_barcodes_i5.tsv
    bc_revcomp: 
      I1: True
      I2: True
    max_barcode_dist: 1

mapping:
  index: /srv/scratch/surag/pipeline/GRCh38_noalt_as/GRCh38_noalt_as
  multimapping: 4

blacklist: /oak/stanford/groups/akundaje/atwang/genomes/hg38/annotations/hg38.blacklist.bed

