workdir: /mnt/lab_data2/atwang/data/encode_scatac/test_all_3/

max_threads_per_rule: 4
seed: 8757647

### END-TO-END TEST DATASET ###

genome: hg38

samples:
  H1:
    technology: 10x
    fastq:
      R1: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/H1_S1_L001_R1_001.fastq.gz
      R2: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/H1_S1_L001_R2_001.fastq.gz
      R3: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/H1_S1_L001_R3_001.fastq.gz
    bc_whitelist: 
      R2: /srv/scratch/surag/chromap_misc/737K-cratac-v1.rc.txt
    bc_revcomp: 
      R2: False
    max_barcode_dist: 2
  D14:
    technology: 10x
    fastq:
      R1: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/D14_S8_L001_R1_001.fastq.gz
      R2: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/D14_S8_L001_R2_001.fastq.gz
      R3: /mnt/lab_data2/atwang/data/encode_scatac/test/scATAC-reprog/fastq/D14_S8_L001_R3_001.fastq.gz
    bc_whitelist: 
      R2: /srv/scratch/surag/chromap_misc/737K-cratac-v1.rc.txt
    bc_revcomp: 
      R2: False
    max_barcode_dist: 2

mapping:
  index: /srv/scratch/surag/pipeline/GRCh38_noalt_as/GRCh38_noalt_as
  multimapping: 4

blacklist: /oak/stanford/groups/akundaje/atwang/genomes/hg38/annotations/hg38.blacklist.bed

