out_prefix: /mnt/lab_data2/atwang/data/encode_scatac/test/
log_prefix: /mnt/lab_data2/atwang/data/encode_scatac/test/logs/
temp_prefix: /srv/scratch/atwang/encode_scatac_

max_threads: 8
seed: 8757647

### ARCHR TEST DATASET ###

genome: hg19

atac_samples: 
  - scATAC_BMMC_R1
  - scATAC_CD34_BMMC_R1
  - scATAC_PBMC_R1

fragments_prefix: /mnt/lab_data2/atwang/data/encode_scatac/test/HemeFragments/
fragments_suffix: .fragments.tsv.gz

# atac_samples: 
#   - atac_v1_pbmc_10k

# fragments_prefix: /mnt/lab_data2/atwang/data/encode_scatac/test/PBMC/
# fragments_suffix: _fragments.tsv.gz